apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  clusterIP: 10.3.240.20 # Switching to ClusterIP since DNS isn't resolving consistently.
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
#  type: "LoadBalancer"
